config/routes.rb
Rails.application.routes.draw do
  # resources :notes 
  resources :subjects do
  	resources :notes 
  end
  root 'subjects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show

    @note = Note.find(params['id'])
    @subject = Subject.find(params['subject_id'])



  end

  # GET /notes/new
  def new
    @subject = Subject.find(params['subject_id'])
    @note = Note.new
    @action = params['action']
  end

  # GET /notes/1/edit
  def edit

    @subject = Subject.find(params['subject_id'])
    @note = Note.find(params['id'])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @subject = Subject.find(params['subject_id'])

    @note.subject_id = @subject.id

    respond_to do |format|
      if @note.save
        @subject.notes << @note
        format.html { redirect_to [@subject, @note], notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    @subject = Subject.find(params['subject_id'])
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to [@subject, @note], notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:name, :content, :subject_id)
    end
  end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @note = Note.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/application_helper.rb
# ArgumentError in Notes#show
# Showing /home/user/Desktop/software/proyectos_ruby_on_rails_2020/everNote/app/views/notes/show.html.erb where line #11 raised:

# Symbol or String expected, but NilClass given.

# Actually, this is a problem with CodeRay, not with Redcarpet.
#  You didn't provide any Markdown but I guess you didn't specify 
#  the language using a fenced code block and language ends up being 
#  nil when block_code is called. You should certainly rather define a 
#  default language to pass to CodeRay in case you didn't specify it in 
#  	your Markdown or use the plain-old indented code blocks:

# CodeRay.scan(code, language || :text).div

module ApplicationHelper
	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			# CodeRay.scan(code, language).div
			CodeRay.scan(code, language || :text).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
		options = {
			:fenced_code_blocks => true,
			:no_intra_emphasis => true,
			:autolink => true,
			:strikethrough => true,
			:lax_html_blocks => true,
			:superscript => true,
			:tables => true,
			:quote => true,
		}
		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end
end

app/helpers/notes_helper.rb
module NotesHelper
	def button_text_note(action)
		action == 'new' ? 'Crear nota': 'Editar nota'
	end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
 <%= form_with(model: [@subject, @note] ) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, 'Título' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content, 'Descripción' %>
    <%= form.text_area :content, col: 10, rows: 15, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit button_text_note(@action), class:'btn btn-light' %>
  </div>
  
<% end %>

app/views/notes/edit.html.erb
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9 ">
			<h1>Editar nota</h1>
			<%= render 'form', note: @note %>
		</div>
	</div>
</div>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.name %></td>
        <td><%= note.content %></td>
        <td><%= note.subject %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9 ">

			<div style="margin-bottom: 30px;margin-top: 30px" ></div>

			<div class="d-flex flex-row justify-content-between">
				<h1>Nueva nota</h1>

				<!-- Button trigger modal -->
				<button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#exampleModal">
					Info markdown
				</button>

				<!-- Modal -->
				<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
					<div class="modal-dialog" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							</div>
						</div>
					</div>
				</div>



































			</div>
			
			<%= render 'form', note: @note %>
		</div>
	</div>
</div>

app/views/notes/show.html.erb
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9 ">
			<div style="margin-bottom: 30px;margin-top: 30px">
			</div>
			<div class="card">
				<div class="card-header d-flex flex-row  justify-content-center">
					<%= @note.name %>
				</div>
				<div class="card-body">
					<%= markdown(@note.content) %>
				</div>
			</div>
			<br>
			<div class="d-flex flex-row ">
				<%= link_to 'devolverse', subject_path(@subject), class:'btn btn-light' %>
				<div style="width:20px"></div>
				
				<%= link_to 'Editar nota', edit_subject_note_path(@subject,@note), class:'btn btn-light' %>
				<%= link_to 'Edit', edit_subject_note_path(@subject,@note) %>
						<%= link_to 'Destroy', subject_note_path(@subject,@note), method: :delete, data: { confirm: 'Are you sure?' } %>
			</div>
		</div>
	</div>
</div>

app/views/subjects/_form.html.erb
  
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Crear tema ', class: 'btn btn-light btn-sm' %>
  </div>
  <br>
<% end %>

app/views/subjects/edit.html.erb
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9 ">
			<h2>Editar tema</h2>
			<%= render 'form', subject: @subject %>
			<%= link_to 'Show', @subject %> |
			<%= link_to 'Back', subjects_path %>
		</div>
	</div>
</div>

app/views/subjects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <div style="margin-bottom: 30px;margin-top: 30px" class="d-flex flex-row  justify-content-between">
        <h2>Temas</h2>
        <%= link_to 'Nuevo tema', new_subject_path , class: 'btn btn-light btn-sm'%>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @subjects.each do |subject| %>
          <tr>
            <td><%= subject.name %></td>
            <td><%= link_to 'Show', subject %></td>
            
            <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="container-fluid h-100">
    <div class="row justify-content-center align-items-center h-100">
        <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">
            <div style="display: flex;justify-content: space-between;margin-bottom: 30px;margin-top: 30px">

				<h2>Crear nuevo tema</h2>
			</div>



			<%= render 'form', subject: @subject %>

			<%= link_to 'Back', subjects_path, class: 'btn btn-light btn-sm' %>
        </div>
    </div>
</div>

app/views/subjects/show.html.erb
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<!-- <div class="col"> -->
			<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9">


				

				<div style="margin-bottom: 30px;margin-top: 30px">
				</div>
				<div class="d-flex flex-row  justify-content-between">
					<%= link_to 'Devolverse', subjects_path,class: 'btn btn-light' %>
				</div>
				<div class="d-flex flex-row  justify-content-between">
					<h2>Temas de <%= @subject.name %></h2>
					<%= link_to 'Nueva nota', new_subject_note_path(@subject), class:'btn btn-light' %>
				</div>
				<br>


				<div class="row">
					<% @subject.notes.each do |note|%>
					<div class=" col-xs-1 col-sm-3 col-md-3 col-lg-3 col-xl-3">



						<%= link_to [@subject,note] do  %>
						<ul>
							<li><%= note.name %></li>
						</ul>
						<% end   %>

						

					</div>
					<% end %>
				</div>

				



			</div>
		</div>
	</div>

















<!-- 
<div class="container-fluid h-100">
	<div class="row justify-content-center align-items-center h-100">
		<div class="col col-sm-9 col-xl-9 col-md-9 col-lg-9">
			

			<div style="margin-bottom: 30px;margin-top: 30px">
			</div>
			<div class="d-flex flex-row  justify-content-between">
				<%= link_to 'Devolverse', subjects_path,class: 'btn btn-light' %>
			</div>
			<div class="d-flex flex-row  justify-content-between">
				<h2>Temas de <%= @subject.name %></h2>
				<%= link_to 'Nueva nota', new_subject_note_path(@subject), class:'btn btn-light' %>
			</div>
			<br>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Notas</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @subject.notes.each do |note|%>
					<tr>
						<td><%= note.name %></td>
						<td><%= link_to 'Show', [@subject,note] %></td>
						<td><%= link_to 'Edit', edit_subject_note_path(@subject,note) %></td>
						<td><%= link_to 'Destroy', subject_note_path(@subject,note), method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
 -->